import Head from 'next/head'
import Layout from '@/components/layout'
import type { NextPageWithLayout } from 'next'
import { useFetchUsersQuery } from '../../generated/graphql.ts'

const Play: NextPageWithLayout = () => {
  const { data, loading, error } = useFetchUsersQuery()
  console.log(data)
  console.log(loading)
  console.log(error)
  return (
    <div>
      <Head>
        <title>Play</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      眼で追うことすら不可能
 
      <div>
        {data &&
          data.users.map((user, i) => {
            return (
              <div key={i}>
                <span>{user.id}</span>
                <span>{user.name}</span>
              </div>
            )
          })}
      </div>
    </div>
  )
}
Play.getLayout = (page) => <Layout>{page}</Layout>

export default Play
